"""create_employees_and_guest_house_tables

Revision ID: a25606802439
Revises: 
Create Date: 2026-09-08 15:33:52.168886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a25606802439'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('employee_name', sa.String(length=300), nullable=False),
    sa.Column('designation', sa.String(length=150), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('email_id', sa.String(length=150), nullable=True),
    sa.Column('employee_status', sa.String(length=50), nullable=True),
    sa.Column('contact_no', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=150), nullable=True),
    sa.Column('source_view', sa.String(length=100), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_index(op.f('ix_employees_department'), 'employees', ['department'], unique=False)
    op.create_index(op.f('ix_employees_email_id'), 'employees', ['email_id'], unique=False)
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employees_employee_status'), 'employees', ['employee_status'], unique=False)
    op.create_table('guest_house_requests',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('guest', sa.String(length=255), nullable=False),
    sa.Column('checkin', sa.String(length=50), nullable=False),
    sa.Column('checkout', sa.String(length=50), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('rejected_at', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['employees.employee_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guest_house_requests')
    op.drop_index(op.f('ix_employees_employee_status'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_email_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_department'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
